### ISSUE TITLE
manage.py migrate

### ISSUE THREAD

**Issue by ktitimbo** [delneg/noteshrinker-django#1]
I am getting this message 
python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'

**Comment by delneg** [comment]
These  can help you
http://stackoverflow.com/questions/9462212/import-error-no-module-named-django
http://stackoverflow.com/questions/24057015/manage-py-importerror-no-module-named-django
Also people suggest
sudo pip3 install Django
